name: Clean New Data

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*.csv'
      - '**/*.xlsx'

jobs:
  clean-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install pandas numpy requests openpyxl

    - name: Detect changed file
      id: detect_file
      run: |
        changed_file=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '\.csv$|\.xlsx$' | head -n 1 || true)
        echo "Changed file: $changed_file"
        echo "CHANGED_FILE=$changed_file" >> $GITHUB_ENV
  
    - name: Run data cleaning script
      if: env.CHANGED_FILE != ''
      run: |
        echo "Cleaning file: ${{ env.CHANGED_FILE }}"
        python clean_data_script.py "${{ env.CHANGED_FILE }}"

    - name: Commit cleaned data
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add *_CLEANED.csv
        git commit -m "Automated: Cleaned $CHANGED_FILE"
        git push
      continue-on-error: true
